trelte-common: validity: whitelist priv-app permission
This fixes bootloop due to

java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.validity.fingerprint: android.permission.INTERACT_ACROSS_USERS}